# MongoDB
MONGO_HOST: prod-db-server  # Replace with your production MongoDB host
MONGO_PORT: 27017
MONGO_DATABASE: cashdb

# Server
CONTAINER_PORT: 8081  # Use a different port for production
ACTIVE_PROFILE: prod

#mpesa
CONSUMER_KEY: KfE72Dp72BGFYdtJWUCAsyl1yGtiPPAA4YzWbprGHFFTsXyK
CONSUMER_SECRET: XMMqk4pqmy8Q14lzBeZ41VFO7HxXDiRrWXfA5b5axpfnda6GHpNsgBb7zh0GDQAv
ACCESS_URL: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
PAYMENT_URL: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
BUSINESS_SHORT_CODE: 174379
PASSKEY: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
CALL_BACK_URL: https://363d-102-210-221-2.ngrok-free.app/callback
